on:
  push:
    branches: [ "main" ]
name: Deploy Bot
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    # This github actions checks out the code of our repo
    # so that the files are available to the action
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        aws-region: '${{ secrets.AWS_REGION }}'
    # Here we run terraform init
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
    # Here we run terraform plan
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'plan'
